name    'puppetlabs-cloudkick'
version '0.0.1'
source 'UNKNOWN'
author 'puppetlabs'
license 'Apache, Version 2.0'
summary 'A module for installing and managing Cloudkicn nodes'
description 'UNKNOWN'
project_page 'http://github.com/jamtur01/puppetlabs-cloudkick'
